version: "3.9"
services:
  exporter:
    image: punkoi/starlink_exporter:v1.0
    environment:
      - STARLINK_ADDRESS=http://dishy.starlink.com:9200
  prometheus:
    image: "prom/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1w'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      -  ./prom_data:/prometheus

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=12345
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources/
      - ./dashboards:/etc/grafana/provisioning/dashboards/
